#pragma once

#include "CPhysical.h"

struct CVehicleGTA : CPhysical {
    uint8_t m_VehicleAudioEntity[588];
    uintptr_t* m_pHandlingData;
    uintptr_t* pFlyingHandling;
    uint32_t m_nHandlingFlagsIntValue;
    uint8_t AutoPilot[152];
    uint32_t m_nVehicleUpperFlags;
    uint32_t m_nVehicleLowerFlags;

    unsigned int m_nCreationTime;
    uint8_t m_nPrimaryColor;
    uint8_t m_nSecondaryColor;
    uint8_t m_colour3;
    uint8_t m_colour4;
    uint8_t m_comp1;
    uint8_t m_comp2;
    short  m_anUpgrades[15];
    float m_wheelScale;
    unsigned short m_nAlarmState;
    short  m_nForcedRandomRouteSeed;
    uintptr_t* pDriver;
    uintptr_t* m_apPassengers[8];
    unsigned char  m_nNumPassengers;
    unsigned char  m_nNumGettingIn;
    unsigned char  m_nGettingInFlags;
    unsigned char  m_nGettingOutFlags;
    uint8_t             m_nMaxPassengers;
    uint8_t             m_nWindowsOpenFlags;
    uint8_t             m_nNitroBoosts;
    int8_t              m_vehicleSpecialColIndex;
    uintptr_t* m_pEntityWeAreOn;
    uintptr_t* m_pFire;
    float  m_fSteerAngle;
    float  m_f2ndSteerAngle;
    float  m_fGasPedal;
    float  m_fBreakPedal;
    uint8_t  m_nCreatedBy;
    unsigned char  abc1;
    unsigned char  abc2;
    unsigned char  abc3;
    uint32_t cachedTotalSteer;
    short m_nExtendedRemovalRange;
    uint8_t m_nBombOnBoard;
    uint8_t m_nOverrideLights;
    uint8_t nUsedForCover;
    uint8_t AmmoInClip;
    uint8_t PacMansCollected;
    uint8_t PedsPositionForRoadBlock;
    uint8_t NumPedsForRoadBlock[4];
    float   m_fDirtLevel;
    unsigned char m_nCurrentGear;
    uint8_t padd_1[3];
    float   m_fGearChangeCount;
    float   m_fWheelSpinForAudio;
    float fHealth;
    CVehicleGTA* m_pTowingVehicle;
    CVehicleGTA* m_pTrailer;
    uint8_t padd_2[3];
    bool m_bFireAutoFlare;
    CEntityGTA *pBombOwner;
    uint32_t DontUseSmallerRemovalRange;
    uint32_t TimeOfLastShotFired;
    uint32_t m_nTimeOfDeath;
    uint16_t GetOutOfCarTimer;
    uint16_t DelayedExplosion;
    CEntityGTA *pDelayedExplosionInflictor;
    float LastFrontHeight;
    float LastRearHeight;
    uint8_t NumOilSpillsToDo;
    uint8_t skip14[3];
    float OilSpillLastX;
    float OilSpillLastY;
    uint32_t m_nDoorLock;
    uint32_t m_LastTimePrimaryFired;
    uint32_t m_LastTimeSecondaryFired;
    uint32_t m_LastTimeGunFired;
    int8_t LastDamagedWeaponType;
    uint8_t skip15[3];
    CEntityGTA *pLastDamageEntity;
    uint8_t m_nRadioStation;
    uint8_t m_nRainHitCount;
    uint8_t m_nSoundIndex;
    uint8_t m_SelectedWeapon;
    uint32_t m_cHorn;
    uint8_t m_nHornPattern;
    uint8_t m_NoHornCount;
    uint8_t ComedyControlsState;
    uint8_t m_hassleStatus;

    uint8_t StoredCollPolys[0x58];
    uint8_t m_storedCollisionLighting[4];
    uintptr_t *m_fxSysEngOverheat;
    uintptr_t *m_fxSysEngFire;
    uintptr_t *m_fxSysHeliDust;
    uint8_t m_nRenderLightsFlags;
    uint8_t skip16[3];
    uintptr_t*   m_pCustomCarPlate;
    float        m_fRawSteerAngle;
    uint32_t     m_nVehicleType;
    uint32_t     m_nVehicleSubType;
    const char* m_remapTxdName;
    const char* m_newRemapTxdName;
    uintptr_t* m_pRemapTexture;
};
