#pragma once
#include <stdint.h>

enum eEntityStatus : uint8_t {
    STATUS_PLAYER = 0,
    STATUS_PLAYER_PLAYBACK_FROM_BUFFER,
    STATUS_SIMPLE,
    STATUS_PHYSICS,
    STATUS_ABANDONED,
    STATUS_WRECKED,
    STATUS_TRAIN_MOVING,
    STATUS_TRAIN_NOT_MOVING,
    STATUS_REMOTE_CONTROLLED,
    STATUS_FORCED_STOP,
    STATUS_IS_TOWED,
    STATUS_IS_SIMPLE_TOWED,
    STATUS_GHOST
};
